apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: https://api.pushover.net/1/messages.json
    - name: method
      value: POST
    - name: contentType
      value: application/json
# key a23krer2j5ic5xqhjmtrop25uw8dcg