/*
 * Todo API
 *
 * A simple Todo API
 *
 * API version: 1.0.0
 * Contact: darko@krizic.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
	errorHandler ErrorHandler
}

// DefaultApiOption for how the controller is set up.
type DefaultApiOption func(*DefaultApiController)

// WithDefaultApiErrorHandler inject ErrorHandler into controller
func WithDefaultApiErrorHandler(h ErrorHandler) DefaultApiOption {
	return func(c *DefaultApiController) {
		c.errorHandler = h
	}
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer, opts ...DefaultApiOption) Router {
	controller := &DefaultApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateTodo",
			strings.ToUpper("Post"),
			"/api/v1/todos",
			c.CreateTodo,
		},
		{
			"DeleteTodo",
			strings.ToUpper("Delete"),
			"/api/v1/todos/{todoId}",
			c.DeleteTodo,
		},
		{
			"GetAllTodos",
			strings.ToUpper("Get"),
			"/api/v1/todos",
			c.GetAllTodos,
		},
		{
			"GetTodo",
			strings.ToUpper("Get"),
			"/api/v1/todos/{todoId}",
			c.GetTodo,
		},
		{
			"UpdateTodo",
			strings.ToUpper("Put"),
			"/api/v1/todos/{todoId}",
			c.UpdateTodo,
		},
	}
}

// CreateTodo - Create a todo
func (c *DefaultApiController) CreateTodo(w http.ResponseWriter, r *http.Request) {
	todoParam := Todo{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&todoParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTodoRequired(todoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateTodo(r.Context(), todoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeleteTodo - Delete a todo
func (c *DefaultApiController) DeleteTodo(w http.ResponseWriter, r *http.Request) {
	todoIdParam := chi.URLParam(r, "todoId")
	
	result, err := c.service.DeleteTodo(r.Context(), todoIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetAllTodos - Get all todos
func (c *DefaultApiController) GetAllTodos(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAllTodos(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetTodo - Get a todo
func (c *DefaultApiController) GetTodo(w http.ResponseWriter, r *http.Request) {
	todoIdParam := chi.URLParam(r, "todoId")
	
	result, err := c.service.GetTodo(r.Context(), todoIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UpdateTodo - Update a todo
func (c *DefaultApiController) UpdateTodo(w http.ResponseWriter, r *http.Request) {
	todoIdParam := chi.URLParam(r, "todoId")
	
	todoParam := Todo{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&todoParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTodoRequired(todoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateTodo(r.Context(), todoIdParam, todoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
