/*
 * Todo API
 *
 * A simple Todo API
 *
 * API version: 1.0.0
 * Contact: darko@krizic.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	todo "github.com/GIT_USER_ID/GIT_REPO_ID/."
)

func main() {
	log.Printf("Server started")

	DefaultApiService := todo.NewDefaultApiService()
	DefaultApiController := todo.NewDefaultApiController(DefaultApiService)

	router := todo.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
