/*
 * Todo API
 *
 * A simple Todo API
 *
 * API version: 1.0.0
 * Contact: darko@krizic.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo
// TodoStatus : Status of the todo
type TodoStatus string

// List of TodoStatus
const (
	ACTIVE TodoStatus = "ACTIVE"
	COMPLETED TodoStatus = "COMPLETED"
	DELETED TodoStatus = "DELETED"
)

// AssertTodoStatusRequired checks if the required fields are not zero-ed
func AssertTodoStatusRequired(obj TodoStatus) error {
	return nil
}

// AssertRecurseTodoStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TodoStatus (e.g. [][]TodoStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTodoStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTodoStatus, ok := obj.(TodoStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTodoStatusRequired(aTodoStatus)
	})
}
