FROM golang:1.19 as builder
COPY /api /build/api
COPY /server /build/server
WORKDIR /build/server
ENV GOOS=linux
ENV GOARCH=arm64
RUN go build -ldflags="-extldflags=-static" -o server server.go

FROM scratch
COPY --from=builder /build/server/server /server
ENTRYPOINT ["/server"]
