image:
  pullPolicy: Always
resources:
  limits:
      cpu: 100m
      memory: 128Mi
  requests:
      cpu: 100m
      memory: 128Mi
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: echo.home.krizic.net
      paths:
        - path: /
          pathType: ImplementationSpecific
nodeSelector:
  kubernetes.io/arch: arm64
deploymentAnnotations:
  sidecar.jaegertracing.io/inject: jaeger
podAnnotations:
  dapr.io/app-id: echo
  dapr.io/app-port: "8000"
  dapr.io/enabled: "true"
  dapr.io/sidecar-cpu-limit: "100m"
  dapr.io/sidecar-memory-limit: "128Mi"
  dapr.io/sidecar-cpu-request: "100m"
  dapr.io/sidecar-memory-request: "128Mi"
  dapr.io/config: "tracing"
