image:
  pullPolicy: Always
resources:
  limits:
      cpu: 100m
      memory: 128Mi
  requests:
      cpu: 100m
      memory: 128Mi
nodeSelector:
  kubernetes.io/arch: arm64
ingress:
  http:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      external-dns: "true"
      external-dns.alpha.kubernetes.io/access: public
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/target: 130.180.93.142
    hosts:
      - host: todo.krizic.net
        paths:
          - path: /api
            pathType: ImplementationSpecific
    tls:
      - secretName: todo-tls
        hosts:
          - todo.krizic.net
  grpc:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      external-dns: "true"
      external-dns.alpha.kubernetes.io/access: public
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      external-dns.alpha.kubernetes.io/target: 130.180.93.142
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
      - host: todo.krizic.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: todo-tls
        hosts:
          - todo.krizic.net
backend:
  type: redis
  redis:
    host: redis-master
metrics:
  serviceMonitor:
    enabled: true
deploymentAnnotations:
  sidecar.jaegertracing.io/inject: jaeger
podAnnotations:
  dapr.io/app-id: todo
  dapr.io/app-port: "8080"
  dapr.io/enabled: "true"
  dapr.io/metrics-port: "9091"
  dapr.io/sidecar-cpu-limit: "100m"
  dapr.io/sidecar-memory-limit: "128Mi"
  dapr.io/sidecar-cpu-request: "100m"
  dapr.io/sidecar-memory-request: "128Mi"
  dapr.io/config: "tracing"
notifications:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60
