apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  TODO_HTTP_PORT: "{{ .Values.service.http.port }}"
  TODO_GRPC_PORT: "{{ .Values.service.grpc.port }}"
  TOOO_HEALTH_PORT: "{{ .Values.service.health.port }}"
  TODO_METRICS_PORT: "{{ .Values.service.metrics.port }}"
  TODO_REDIS_HOST: "{{ .Values.backend.redis.host }}"
  TODO_REDIS_PORT: "{{ .Values.backend.redis.port | toString }}"
  TODO_REDIS_USER: "{{ .Values.backend.redis.user }}"
  TODO_REDIS_DB: "{{ .Values.backend.redis.db | toString}}"
  TODO_MEMORY_MAXENTRIES: "{{ .Values.backend.memory.maxEntries | toString}}"
  TODO_NOTIFICATIONS_ENABLED: "{{ .Values.notifications.enabled | toString }}"
  TODO_NOTIFICATIONS_PUBSUB_NAME: "{{ .Values.notifications.pubsub.name }}"
  TODO_NOTIFICATIONS_PUBSUB_TOPIC: "{{ .Values.notifications.pubsub.topic }}"
  TODO_TRACING_ENABLED: "{{ .Values.tracing.enabled | toString }}"
  TODO_TRACING_ENDPOINT: "{{ .Values.tracing.endpoint }}"
