apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  TODO_REDIS_HOST: "{{ .Values.backend.redis.host }}"
  TODO_REDIS_PORT: "{{ .Values.backend.redis.port | toString }}"
  TODO_REDIS_USER: "{{ .Values.backend.redis.user }}"
  TODO_REDIS_DB: "{{ .Values.backend.redis.db | toString}}"
  TODO_MEMORY_MAXENTRIES: "{{ .Values.backend.memory.maxEntries | toString}}"
