apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  TODO_REDIS_HOST: {{ .Values.backend.redis.host | b64enc }}
  TODO_REDIS_PORT: {{ .Values.backend.redis.port | b64enc }}
  TODO_REDIS_USER: {{ .Values.backend.redis.user | b64enc }}
  TODO_REDIS_DB: {{ .Values.backend.redis.db | b64enc }}
  TODO_MEMORY_MAXENTRIES: {{ .Values.backend.memory.maxEntries | b64enc }}
