on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Set the version to tag if it exists otherweise take the commit short hash
      - name: Set version
        id: version
        run: |
          if [[ -n "${GITHUB_REF##*/}" ]]; then
              echo "::set-output name=version::${GITHUB_REF##*/}"
          else
              echo "::set-output name=version::${GITHUB_SHA::7}"
          fi

  ci-amd64:
    runs-on: ubuntu-latest
    needs: version
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Build docker image
      - name: Build docker image
        run:  docker build -t todo-server-amd64:latest -f server/docker/Dockerfile.amd64 .

  ci-arm64:
    runs-on: ubuntu-latest
    needs: version
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Build docker image
      - name: Build docker image
        run:  docker build -t todo-server-arm64:latest -f server/docker/Dockerfile.arm64 .
