on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Set the version to tag if it exists otherweise take the commit short hash
      - name: Set version
        id: version
        run: |
          if [[ -n "${GITHUB_REF##*/}" ]]; then
              echo "version=${GITHUB_REF##*/}" >>$GITHUB_OUTPUT
          else
              echo "version=${GITHUB_SHA::7}" >>$GITHUB_OUTPUT
          fi
      - name: Print version
        run: echo ${{ steps.version.outputs.version }}

  ci-amd64:
    runs-on: ubuntu-latest
    needs: version
    steps:
      # checkout code
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build docker image
      - name: Build docker image
        run:  docker build -t ${{ env.REGISTRY}}/${{ github.actor }}/todo-server-amd64:latest -f server/docker/Dockerfile --build-arg ARCH=amd64 .

      - name: Push docker image
        run: docker push ${{ env.REGISTRY}}/${{ github.actor }}/todo-server-amd64:latest

  ci-arm64:
    runs-on: ubuntu-latest
    needs: version
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Build docker image
      - name: Build docker image
        run:  docker build -t ${{ env.REGISTRY}}/${{ github.actor }}/todo-server-arm64:latest -f server/docker/Dockerfile --build-arg ARCH=arm64 .

      - name: Push docker image
        run: docker push ${{ env.REGISTRY}}/${{ github.actor }}/todo-server-arm64:latest