on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:

  ci-amd64:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Build docker image
      - name: Build docker image
        run:  docker build -t todo-server-amd64:latest -f server/docker/Dockerfile.amd64 .

  ci-arm64:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Build docker image
      - name: Build docker image
        run:  docker build -t todo-server-arm64:latest -f server/docker/Dockerfile.ard64 .
