on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:

  ci-amd64:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # Install go
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # Compile server
      - name: Compile server
        working-directory: /build/server
        run: go build -o server server.go

      # Build docker image
      - name: Build docker image
        working-directory: /build/server
        run:  docker build -t todo-server:amd64 -f server/docker/Dockerfile.amd64 .
