apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  metric:
    enabled: true
  tracing:
    samplingRate: "1"
    stdout: true
    #zipkin:
    #  endpointAddress: http://localhost:9412/api/v2/spans
    otel:
      endpointAddress: "localhost:4317"
      isSecure: false
      protocol: "grpc"

