apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  metric:
    enabled: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://jaeger-collector.observability:9411/api/v2/spans
    #otel:
    #  endpointAddress: "localhost:4317"
    #  isSecure: false


