apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  metric:
    enabled: true
  tracing:
    samplingRate: "1"
    #otel:
    #  endpointAddress: "otel-collector.observability:4317"
    #  isSecure: false
    #  protocol: grpc
    zipkin:
      endpointAddress: "http://otel-collector.observability:9411/api/v2/spans"
